apiVersion: v1
data:
  policy.csv: |
    g, serviceuser, role:admin
  policy.default: role:readonly
  scopes: '[groups]'
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: argocd
    meta.helm.sh/release-namespace: argocd
  creationTimestamp: "2023-06-01T15:07:24Z"
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
    helm.sh/chart: argo-cd-5.32.1
  name: argocd-rbac-cm
  namespace: argocd
  resourceVersion: "3204"
  uid: b3becd09-1682-40db-9f99-25f6383c5621
