apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'checker'
spec:
  project: default
  source:
    repoURL: 'https://github.com/acadnet-dev/infra.git'
    path: charts/checker
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.tag
          value: 84a86cfc72bc2cd85b254a4c0e8a005f25c474e2
      values: |-
        image:
          tag: latest
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: acadnet
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
