apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.labels.name }}
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: {{ .Values.labels.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.name }}
    spec:
      containers:
        - name: {{ .Values.labels.name }}-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: "Always"
          ports:
            - containerPort: {{ .Values.service.port }}
      imagePullSecrets:
        - name: ghcr-login-secret